### ISSUE TITLE
HMR nuking the store?

### ISSUE THREAD

**Issue by dimatter** [PhillMcKraken/enhanced-electron-react-boilerplate#2]
what is the point of hot reload if ones state is being killed on every change?

...or have I messed something up?

**Comment by pbarbiero** [comment]
You need to set up your app yourself to accept HMR. Webpack is only configured to enable it. See https://webpack.js.org/guides/hmr-react/ for more info.

`react-hot-loader` is integrated, but thats only the react side. Redux is separate and would have to be handled by you.

**Comment by dimatter** [comment]
thanks

**Comment by dimatter** [comment]
I've figured this out. The problem is that components.js, where the store is being initialized is including all **/component.js, which in turn include their React component.

for a component Foo, the dependency tree will be Foo => component.js => components.js => **root**

that is why the whole app is re-rendered & new store is generated upon editing any child component.

**Comment by paulinhapenedo** [comment]
@dimatter how did you solve this problem?

**Comment by nurpax** [comment]
I think I fixed this bug in my PR to upgrade to latest webpack, react, redux:

https://github.com/pbarbiero/enhanced-electron-react-boilerplate/pull/15/commits/c9dea20c979b57246bab847fb45c6a54148492fe
